version: '3'

networks:
  webapp:

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    restart: unless-stopped
    tty: true   
    environment:
      SERVICE_NAME: app
      SERVICE_TAG: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/user/loacl/etc/php/conf.d/local.ini
    networks:
      - webapp

  node:
    image: node:19
    container_name: ${APP_NAME}_node
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - webapp
    tty: true


  nginx:
    env_file:
      - .env
    image: nginx:1.16.1
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    tty: true
    ports:
    - "80:80"
    - "443:443"    
    volumes:
      - ./:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw      
    networks:
      - webapp  

  postgres:
    env_file:
      - .env
    image: postgres:12.3    
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      PGUSER: postgres
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"
      SERVICE_NAME: postgresql
      SERVICE_TAG: dev
    networks:
      - webapp
