name: publish
on: [push]
jobs:
laravel-docker:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the docker-app Docker image
run: |
       docker build . --tag ghcr.io/deselikem/docker-app:latest
       docker run ghcr.io/docker-app:latest
       docker push ghcr.io/docker-app:latest